version: '3.8'

services:
  web:
    build: .
    #to production consider to use gunicorn in order to improve the performance and concurrence.
    #command: gunicorn TalaTask.wsgi:application --bind 0.0.0.0:8000,
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
