# Generated by Django 5.1 on 2024-08-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_skill_alter_employee_available_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.ManyToManyField(to='tasks.skill'),
        ),
    ]
