# Generated by Django 5.1 on 2024-08-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_required_skills_task_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='available_hours_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
